"""criaçao de pagination

Revision ID: b2fd03f71d52
Revises: 609709f0d213
Create Date: 2021-12-13 10:30:10.355382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fd03f71d52'
down_revision = '609709f0d213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
